$(document).ready(function(){
    $(".slider-inner").slick({
        infinite:true,
        slidesToshow:3,
        slidesToScroll:1,
        centerMode:true,
        centerPadding:'0px',
        arrows:false,
        autoplay:true,
        autoplaySpeed:1000,
        speed:1500
    });
});